### Import Packages

In [65]:
from selenium import webdriver
import pandas as pd

### Open Link

In [66]:
driver = webdriver.Chrome('C:\WebDriver\chromedriver.exe')

driver.get('https://pokemondb.net/pokedex/all')
driver.maximize_window()

In [67]:
# Policy Policy
button = driver.find_element_by_class_name('gdpr-accept')

try:
    button.click()
except:
    pass

### Create Locators

In [68]:
#name
pokemon_name = driver.find_elements_by_xpath('//tbody/tr/td/a[@class="ent-name"]')

#type
pokemon_type = driver.find_elements_by_xpath('//tbody/tr/td[3]')

#total
pokemon_total = driver.find_elements_by_xpath('//tbody/tr/td[4]')

#HP
pokemon_hp = driver.find_elements_by_xpath('//tbody/tr/td[5]')

#Attack
pokemon_attack = driver.find_elements_by_xpath('//tbody/tr/td[6]')

#Defense
pokemon_defense = driver.find_elements_by_xpath('//tbody/tr/td[7]')

#Sp.Atk
pokemon_sp_attack = driver.find_elements_by_xpath('//tbody/tr/td[8]')

#SP.Def
pokemon_sp_defense = driver.find_elements_by_xpath('//tbody/tr/td[9]')

#Speed
pokemon_speed = driver.find_elements_by_xpath('//tbody/tr/td[10]')

In [82]:
for i in range(len(pokemon_name)):
    print(pokemon_speed[i].text)

45
60
80
80
65
80
100
100
100
43
58
78
78
45
30
70
50
35
75
145
56
71
101
121
72
72
97
77
70
100
55
80
90
120
110
110
40
40
65
65
41
56
76
50
65
85
35
60
65
65
100
109
20
45
55
90
30
40
50
25
30
45
90
95
90
120
110
90
90
40
115
115
55
85
70
95
60
95
90
90
70
90
105
120
150
35
45
55
40
55
70
70
100
20
20
35
35
45
45
90
90
105
105
15
15
30
30
30
45
70
60
55
75
110
45
70
25
25
50
50
40
70
80
95
110
130
70
42
67
50
75
100
150
40
55
45
35
45
45
87
76
30
35
60
60
25
40
50
60
90
100
60
85
63
68
85
115
90
100
105
95
105
93
85
105
110
80
81
81
60
48
55
75
65
130
65
40
35
55
55
80
130
150
30
85
95
100
100
90
90
50
70
80
130
130
140
100
45
60
80
65
80
100
43
58
78
20
90
50
70
55
85
30
40
130
67
67
60
15
15
20
40
70
95
35
45
55
45
50
40
50
30
70
50
80
110
85
30
30
95
15
35
110
65
91
30
30
85
48
33
85
15
40
45
85
30
30
30
45
85
65
75
5
85
75
115
40
55
20
30
50
50
35
30
65
45
75
70
70
65
95
115
85
40
50
60
85
75
35
70
65
95
83
100
55
115
100
85
41
51
61
71
110
90
100
70
95
120
145
45
55
80
100
40
50
60
70
35
70
60
60
100
100
20
15
65
15
65
30
50
70
30
60
80
85
125
85
65
40
50
80
100
65
80
35
70
30
90
100
40
160
40
28
48
68
25
50
20
30
50
90
50
20
50
50
30
40
50
50
60
80
100
65
105
135
95
95
85
85
65
40
55
65
95
105
60
60
35
40
20
20
60
80
60
10
70
100
35
55
50
80
80
90
65
70
70
60
60
35
55
55
75
23
43
75
45
80
81
70
70
70
70
40
45
65
75
25
25
51
65
75
115
23
50
80
100
25
45
65
32
52
52
55
97
50
50
100
120
30
50
70
110
50
50
50
110
110
110
110
90
90
90
90
95
115
100
150
150
90
180
31
36
56
61
81
108
40
50
60
60
80
100
31
71
25
65
45
60
70
55
90
58
58
30
30
36
36
36
36
66
70
40
95
85
115
35
85
34
39
115
70
80
85
105
135
105
71
85
112
45
74
84
23
33
10
60
30
91
35
42
82
102
92
5
60
90
112
32
47
65
95
50
85
46
66
91
50
40
60
30
125
60
50
40
50
95
83
80
95
95
65
95
80
90
80
110
40
45
110
91
86
86
86
86
86
95
80
115
90
100
77
100
90
90
85
80
100
125
100
127
120
100
63
83
113
45
55
65
45
60
70
42
77
55
60
80
66
106
64
101
64
101
64
101
24
29
43
65
93
76
116
15
20
25
72
114
68
88
50
50
35
40
45
64
69
74
45
85
42
42
92
57
47
112
66
116
30
90
98
98
65
74
92
50
50
95
55
95
135
60
55
45
48
58
97
30
30
30
22
32
70
110
65
75
65
105
75
115
45
55
65
20
30
30
55
98
44
59
79
75
95
103
60
20
15
30
40
60
65
65
108
10
20
30
50
90
60
40
50
30
40
20
55
80
57
67
97
40
50
105
25
145
32
32
65
105
48
35
55
60
70
55
60
80
60
80
65
109
38
58
98
60
100
108
108
108
111
121
111
101
90
90
101
91
95
95
95
108
108
90
128
99
38
57
64
60
73
104
71
97
122
132
57
78
62
84
126
35
29
89
72
106
42
52
75
52
68
43
58
102
68
104
104
28
35
60
60
23
29
49
72
45
73
50
68
30
44
44
59
70
109
48
71
46
58
60
118
101
50
40
60
80
75
38
56
51
56
46
41
84
99
69
54
28
28
55
123
99
99
95
115
85
50
110
70
80
70
42
52
70
70
90
60
40
50
60
65
75
60
45
45
46
36
43
63
43
93
93
93
93
84
124
60
60
112
82
110
40
30
45
35
45
35
27
42
35
45
15
30
77
117
50
60
32
62
72
100
60
80
80
40
15
35
5
59
95
60
120
65
36
96
96
92
36
40
45
65
85
130
95
75
85
37
37
97
97
103
79
151
83
61
109
43
79
77
77
129
65
125
73
121
13
107
143
34
34
65
80
85
69
94
119
70
90
120
25
20
57
77
67
45
30
90
50
90
10
60
48
88
44
74
26
121
30
50
30
20
70
30
46
71
85
66
136
40
75
75
45
65
32
42
50
70
39
49
29
50
70
60
95
50
30
65
70
30
34
64
75
15
20
65
70
50
130
95
85
97
97
40
30
75
55
75
55
85
82
102
142
148
138
128
138
130
130
72
97
97
105
200
80
30
130
80
50
150

### Empty List

In [83]:
pokemon_results = []

### Dictionary

In [84]:
for i in range(len(pokemon_name)):
    pokemon_dictionary={'Name':pokemon_name[i].text,
                       'Type': pokemon_type_list[i],
                       'Total':pokemon_total[i].text,
                       'HP': pokemon_hp[i].text,
                       'Attack':pokemon_attack[i].text,
                       'Defense': pokemon_defense[i].text,
                       'Sp.Attack': pokemon_sp_attack[i].text,
                       'Sp.Defense': pokemon_sp_defense[i].text,
                       'Speed':pokemon_speed[i].text}
    
    pokemon_results.append(pokemon_dictionary)

### Create Dataframe

In [85]:
dataframe_pokemon = pd.DataFrame(pokemon_results)

In [86]:
dataframe_pokemon

,Name,Type,Total,HP,Attack,Defense,Sp.Attack,Sp.Defense,Speed
0,Bulbasaur,GRASS\nPOISON,318,45,49,49,65,65,45
1,Ivysaur,GRASS\nPOISON,405,60,62,63,80,80,60
2,Venusaur,GRASS\nPOISON,525,80,82,83,100,100,80
3,Venusaur,GRASS\nPOISON,625,80,100,123,122,120,80
4,Charmander,FIRE,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...
1040,Glastrier,ICE,580,100,145,130,65,110,30
1041,Spectrier,GHOST,580,100,65,60,145,80,130
1042,Calyrex,PSYCHIC\nGRASS,500,100,80,80,80,80,80
1043,Calyrex,PSYCHIC\nICE,680,100,165,150,85,130,50
1044,Calyrex,PSYCHIC\nGHOST,680,100,85,80,165,100,150

### Replace Unnecessary Characters

In [87]:
#replace '\n' with '/'
dataframe_pokemon['Name'] = dataframe_pokemon['Name'].apply(lambda x: x.replace ('\n', '/'))

In [88]:
#replace '\n' with a comma
dataframe_pokemon['Type'] = dataframe_pokemon['Type'].apply(lambda x: x.replace ('\n', ','))

In [89]:
# updated dataframe
dataframe_pokemon

,Name,Type,Total,HP,Attack,Defense,Sp.Attack,Sp.Defense,Speed
0,Bulbasaur,"GRASS,POISON",318,45,49,49,65,65,45
1,Ivysaur,"GRASS,POISON",405,60,62,63,80,80,60
2,Venusaur,"GRASS,POISON",525,80,82,83,100,100,80
3,Venusaur,"GRASS,POISON",625,80,100,123,122,120,80
4,Charmander,FIRE,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...
1040,Glastrier,ICE,580,100,145,130,65,110,30
1041,Spectrier,GHOST,580,100,65,60,145,80,130
1042,Calyrex,"PSYCHIC,GRASS",500,100,80,80,80,80,80
1043,Calyrex,"PSYCHIC,ICE",680,100,165,150,85,130,50
1044,Calyrex,"PSYCHIC,GHOST",680,100,85,80,165,100,150

### Dataframe to Excel

In [90]:
dataframe_pokemon.to_excel('pokemon_database_cleaned.xlsx', index=False)